name: Deploy Frontend (Angular)

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ^20.17.19

      - name: Install dependencies
        working-directory: frontend/frontend-app
        run: npm install

      - name: Build Angular App
        working-directory: frontend/frontend-app
        run: npm run build -- --configuration production
      
      - name: Zip Angular build output
        run: |
          cd frontend/frontend-app/dist/frontend-app
          zip -r ../../../frontend.zip .

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "saas5710"  
          publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
          package: frontend/frontend-app/dist
