name: Deploy Shop Service

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Install
        working-directory: shop-service
        run: npm install

      - name: Build
        working-directory: shop-service
        run: npm run build

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: "shopservice"
          publish-profile: ${{ secrets.SHOP_PUBLISH_PROFILE }}
          package: ./shop-service
