name: Deploy Shop Service

on:
  workflow_call:
  secrets:
      SHOP_PUBLISH_PROFILE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install & Build
        working-directory: shop-service
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: "focusmate-shop-service"
          publish-profile: ${{ secrets.SHOP_PUBLISH_PROFILE }}
          package: ./shop-service
